<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tgi.Gegaco.FileUploader.Web</RootNamespace>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
    <IsAspNetCoreSpaProject>true</IsAspNetCoreSpaProject>
	   <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings> 
  </PropertyGroup>

  <!-- Excluir ClientApp/node_modules del proyecto -->
  <ItemGroup>
    <Content Remove="$(SpaRoot)node_modules\**" />
  </ItemGroup>


  <!-- Restaurar dependencias de Angular -->
  <Target Name="NpmInstall" BeforeTargets="Build">
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>
  

	  <!-- Compilar Angular en Producción y copiar los archivos generados -->
	<Target Name="AngularBuild" AfterTargets="Publish" Condition="'$(Configuration)'=='Release'">
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production" />
		<ItemGroup>
			<!-- Incluir SOLO el contenido de dist\ClientApp -->
			<SpaDistFiles Include="$(SpaRoot)dist\ClientApp\**\*" />
		</ItemGroup>
		<!-- Copiar al wwwroot preservando la estructura interna de ClientApp -->
		<Copy SourceFiles="@(SpaDistFiles)" DestinationFiles="@(SpaDistFiles->'wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
	</Target>
	

	<!-- Para que VS ejecute Angular CLI automáticamente en Development -->
   <!-- <Target Name="DebugRunAngular" AfterTargets="Build" Condition="'$(Configuration)'=='Debug'">   -->
     <!-- <Exec WorkingDirectory="$(SpaRoot)" Command="npm start" ContinueOnError="true" />   -->
  <!-- </Target>  -->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tgi.Gegaco.FileUploader.Application\Tgi.Gegaco.FileUploader.Application.csproj" />
    <ProjectReference Include="..\Tgi.Gegaco.FileUploader.Infrastructure\Tgi.Gegaco.FileUploader.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
		<!-- Evita que cualquier archivo bajo ClientApp se copie al publish -->
		<Content Update="ClientApp\**\*">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Content>
		<None Update="ClientApp\**\*">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	
	
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
